id: python-v1
version: 1
runtime: python
lockfileRequired: false
install: python3 -m pip install -r requirements.txt
test: python3 -m pytest
build: python3 .central-cicd/package-python-source.py
artifactPath: artifact
